### ISSUE TITLE
finish multilabel classification

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr#347]
I have pushed now a basic version, after I completely rewrote the PR....

I works now BASICALLY. 

But there is much to do:

Phillip, here is a list:

- doc everything where you think multilable needs to be mentioned, but REALLY explain what the wrapper does and doc it fully

- write as many useful unit tests as possible. I started in base_multilabel. also test probabilities later. 

- write some tutorial pages to explain the multilabel case. get help from @schiffner for that.
IMHO you can completely reuse this for your thesis, though this would be in english. I rather have good info on the web then "dead" in your PDF. 

- we later need to integrate how you measured single measures / columns.
put that code SAFELY away now, it is gone in the mlr master

- we later need to integrate your ROC plots
put that code SAFELY away now, it is gone in the mlr master

stuff for me  
- check output of learner to be log matrix
- as a example task 
- probabilities 
- thresholds

**Comment by IcedragonP** [comment]
Ok, I did some things, but to finish them off and write tests, I will need your proper version with train that works (isn't working for me with the current version and newdata), etc. ;)

Cheers,
Philipp

**Comment by berndbischl** [comment]
There is a unit test? Get on hangout

**Comment by berndbischl** [comment]
I fixed the newdata problem.

How are the scores computed for rFerns? Apparently they can be become negative.

**Comment by IcedragonP** [comment]
ok, but train still does not work in the MultilabelWrapper case:

> data(iris)
> iris <- data.frame(iris,sample(c(T,F),150,replace=T),sample(c(T,F),150,replace=T))
> colnames(iris)[6:7] <- c("neu1","neu2")
> task2 = makeMultilabelTask(id = "multi", data = iris[-c(1:10),], target = c("neu1","neu2"))
> lrn2 = makeLearner("classif.randomForest", par.vals=list(ntree=30))
> lrn2 = makeMultilabelWrapper(lrn2)
> tr2 = train(lrn2,task2)
Error in as.vector(x) : Argument "x" fehlt (ohne Standardwert)
Timing stopped at: 0.004 0 0.004

They are normalised scores. When they are positive they are reported as present, otherwise not.
See paper http://arxiv.org/pdf/1403.7746v1.pdf page 5 and 6.

**Comment by berndbischl** [comment]
mainly done and tested
